# GITHUB CODE

In [1]:
# Cloning the Github repo
!git clone https://github.com/yuh-zha/AlignScore.git
%cd AlignScore

Cloning into 'AlignScore'...
remote: Enumerating objects: 202, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 202 (delta 36), reused 12 (delta 12), pack-reused 153 (from 1)
Receiving objects: 100% (202/202), 523.86 KiB | 10.07 MiB/s, done.
Resolving deltas: 100% (113/113), done.
/content/AlignScore

In [2]:
# Installing teh packages
!pip install -e .
!python -m spacy download en_core_web_sm # --> spacy for sentence splitting

Obtaining file:///content/AlignScore
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting datasets<3,>=2.3.2 (from alignscore==0.1.3)
  Downloading datasets-2.21.0-py3-none-any.whl.metadata (21 kB)
Collecting jsonlines<3,>=2.0.0 (from alignscore==0.1.3)
  Downloading jsonlines-2.0.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: nltk<4,>=3.7 in /usr/local/lib/python3.12/dist-packages (from alignscore==0.1.3) (3.9.1)
Collecting numpy<2,>=1.23.1 (from alignscore==0.1.3)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.0 MB/s eta 0:00:00
Collecting protobuf<=3.20 (from alignscore==0.1.3)
  Downloading protobuf-3.20.0-py2.py3-none-any.whl.metadata (720 bytes)
Collecting pytorch-lightning<2,>=1.7.7 (from alignscore==0.1.3)
  Downloading pytorch_lightning-1.9.5-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scikit-learn<2,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from alignscore==0.1.3) (1.6.1)
Requirement already satisfied: scipy<2,>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from alignscore==0.1.3) (1.16.3)
Requirement already satisfied: spacy<4,>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from alignscore==0.1.3) (3.8.14)
Requirement already satisfied: tensorboard<3,>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from alignscore==0.1.3) (2.20.0)
INFO: pip is looking at multiple versions of alignscore to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement torch<2,>=1.12.1 (from alignscore) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.9.0, 2.9.1, 2.10.0, 2.11.0, 2.12.0, 2.12.1)
ERROR: No matching distribution found for torch<2,>=1.12.1
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 85.6 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [3]:
# checkpoints in the paper --> Alignscore for different models from hugging face
!mkdir ckpt
!wget -O ckpt/AlignScore-base.ckpt https://huggingface.co/yzha/AlignScore/resolve/main/AlignScore-base.ckpt

--2026-06-25 07:21:42--  https://huggingface.co/yzha/AlignScore/resolve/main/AlignScore-base.ckpt
Resolving huggingface.co (huggingface.co)... 3.171.171.65, 3.171.171.104, 3.171.171.128, ...
Connecting to huggingface.co (huggingface.co)|3.171.171.65|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://us.aws.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&user_id=public&Expires=1782375702&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5hd3MuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9YLVhldC1DYXMtVWlkPXB1YmxpYyZyZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWlubGluZSUzQitmaWxlbmFtZSUyQSUzRFVURi04JTI3JTI3QWxpZ25TY29yZS1iYXNlLmNrcHQlM0IrZmlsZW5hbWUlM0QlMjJBbGlnblNjb3JlLWJhc2UuY2twdCUyMiUzQiZ1c2VyX2lkPXB1YmxpYyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzgyMzc1NzAyfX19XX0_&Signature=MEYCIQDix5z3HdhXJ51pvTvS1BYeQFmOjwZaBGghifpzZDmvgAIhAMnfoxKkVb3POdz2G2zeoFP5tgxEWDJLlS-0ykrGDpHW&Key-Pair-Id=01KAYHXK2CBJSW0YZTMNXK9W1M [following]
--2026-06-25 07:21:42--  https://us.aws.cdn.hf.co/xet-bridge-us/647835e2159a889d001bebb4/a1ae41aa60f0f09954a2e05d43602df4f5edd951c2d85092bfc0002bc9a3f8c8?X-Xet-Cas-Uid=public&response-content-disposition=inline%3B+filename*%3DUTF-8%27%27AlignScore-base.ckpt%3B+filename%3D%22AlignScore-base.ckpt%22%3B&user_id=public&Expires=1782375702&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly91cy5hd3MuY2RuLmhmLmNvL3hldC1icmlkZ2UtdXMvNjQ3ODM1ZTIxNTlhODg5ZDAwMWJlYmI0L2ExYWU0MWFhNjBmMGYwOTk1NGEyZTA1ZDQzNjAyZGY0ZjVlZGQ5NTFjMmQ4NTA5MmJmYzAwMDJiYzlhM2Y4YzhcXD9YLVhldC1DYXMtVWlkPXB1YmxpYyZyZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWlubGluZSUzQitmaWxlbmFtZSUyQSUzRFVURi04JTI3JTI3QWxpZ25TY29yZS1iYXNlLmNrcHQlM0IrZmlsZW5hbWUlM0QlMjJBbGlnblNjb3JlLWJhc2UuY2twdCUyMiUzQiZ1c2VyX2lkPXB1YmxpYyIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiRXBvY2hUaW1lIjoxNzgyMzc1NzAyfX19XX0_&Signature=MEYCIQDix5z3HdhXJ51pvTvS1BYeQFmOjwZaBGghifpzZDmvgAIhAMnfoxKkVb3POdz2G2zeoFP5tgxEWDJLlS-0ykrGDpHW&Key-Pair-Id=01KAYHXK2CBJSW0YZTMNXK9W1M
Resolving us.aws.cdn.hf.co (us.aws.cdn.hf.co)... 100.50.185.240, 100.29.213.216, 98.90.123.60, ...
Connecting to us.aws.cdn.hf.co (us.aws.cdn.hf.co)|100.50.185.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1966965771 (1.8G) [application/octet-stream]
Saving to: ‘ckpt/AlignScore-base.ckpt’

ckpt/AlignScore-bas 100%[===================>]   1.83G  21.7MB/s    in 2m 12s

2026-06-25 07:23:55 (14.2 MB/s) - ‘ckpt/AlignScore-base.ckpt’ saved [1966965771/1966965771]

In [5]:
# manually installing some dependencies
!pip install datasets==2.21.0 jsonlines==2.0.0 numpy==1.26.4 protobuf==3.20.0 pytorch-lightning==1.9.5 transformers==4.35.2

Collecting datasets==2.21.0
  Using cached datasets-2.21.0-py3-none-any.whl.metadata (21 kB)
Collecting jsonlines==2.0.0
  Using cached jsonlines-2.0.0-py3-none-any.whl.metadata (1.5 kB)
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting protobuf==3.20.0
  Using cached protobuf-3.20.0-py2.py3-none-any.whl.metadata (720 bytes)
Collecting pytorch-lightning==1.9.5
  Using cached pytorch_lightning-1.9.5-py3-none-any.whl.metadata (23 kB)
Collecting transformers==4.35.2
  Downloading transformers-4.35.2-py3-none-any.whl.metadata (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.5/123.5 kB 4.0 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (3.29.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (3.7.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (0.70.16)
Collecting fsspec<=2024.6.1,>=2023.1.0 (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets==2.21.0)
  Downloading fsspec-2024.6.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (3.14.1)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (1.19.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets==2.21.0) (6.0.3)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning==1.9.5) (2.11.0+cu128)
Collecting torchmetrics>=0.7.0 (from pytorch-lightning==1.9.5)
  Downloading torchmetrics-1.9.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pytorch-lightning==1.9.5) (4.15.0)
Collecting lightning-utilities>=0.6.0.post0 (from pytorch-lightning==1.9.5)
  Downloading lightning_utilities-0.15.3-py3-none-any.whl.metadata (5.5 kB)
Collecting huggingface-hub>=0.21.2 (from datasets==2.21.0)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.35.2) (2025.11.3)
Collecting tokenizers<0.19,>=0.14 (from transformers==4.35.2)
  Downloading tokenizers-0.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.35.2) (0.8.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.21.0) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.21.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.21.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.21.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.21.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.21.0) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets==2.21.0) (1.24.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets==2.21.0) (1.5.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==2.21.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==2.21.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==2.21.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets==2.21.0) (2026.5.20)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.10.0->pytorch-lightning==1.9.5) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.10.0->pytorch-lightning==1.9.5) (12.8.90)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==2.21.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==2.21.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==2.21.0) (2026.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.10.0->pytorch-lightning==1.9.5) (1.5.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==2.21.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.10.0->pytorch-lightning==1.9.5) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.10.0->pytorch-lightning==1.9.5) (3.0.3)
Downloading datasets-2.21.0-py3-none-any.whl (527 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.3/527.3 kB 16.9 MB/s eta 0:00:00
Downloading jsonlines-2.0.0-py3-none-any.whl (6.3 kB)
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 99.5 MB/s eta 0:00:00
Downloading protobuf-3.20.0-py2.py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.1/162.1 kB 15.4 MB/s eta 0:00:00
Downloading pytorch_lightning-1.9.5-py3-none-any.whl (829 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.5/829.5 kB 63.0 MB/s eta 0:00:00
Downloading transformers-4.35.2-py3-none-any.whl (7.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 125.1 MB/s eta 0:00:00
Downloading fsspec-2024.6.1-py3-none-any.whl (177 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 19.2 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 32.9 MB/s eta 0:00:00
Downloading lightning_utilities-0.15.3-py3-none-any.whl (31 kB)
Downloading tokenizers-0.15.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 95.1 MB/s eta 0:00:00
Downloading torchmetrics-1.9.0-py3-none-any.whl (983 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 46.3 MB/s eta 0:00:00
Installing collected packages: protobuf, numpy, lightning-utilities, jsonlines, fsspec, huggingface-hub, tokenizers, transformers, datasets, torchmetrics, pytorch-lightning
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.6
    Uninstalling protobuf-5.29.6:
      Successfully uninstalled protobuf-5.29.6
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.19.0
    Uninstalling huggingface_hub-1.19.0:
      Successfully uninstalled huggingface_hub-1.19.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: transformers
    Found existing installation: transformers 5.12.0
    Uninstalling transformers-5.12.0:
      Successfully uninstalled transformers-5.12.0
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wandb 0.27.2 requires protobuf!=5.28.0,!=5.29.0,<8,>4.21.0, but you have protobuf 3.20.0 which is incompatible.
google-api-core 2.30.3 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery-storage 2.39.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
grain 0.2.17 requires protobuf>=5.28.3, but you have protobuf 3.20.0 which is incompatible.
google-cloud-datastore 2.25.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
google-cloud-dataproc 5.28.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigtable 2.38.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-aiplatform 1.157.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
google-cloud-language 2.20.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
google-cloud-discoveryengine 0.13.12 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
google-cloud-audit-log 0.6.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-bigquery-connection 1.22.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
google-cloud-monitoring 2.31.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-resource-manager 1.17.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-pubsub 2.39.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tensorflow 2.20.0 requires protobuf>=5.28.0, but you have protobuf 3.20.0 which is incompatible.
ydf 0.15.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 3.20.0 which is incompatible.
google-cloud-secret-manager 2.29.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
grpc-google-iam-v1 0.14.4 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-speech 2.40.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-spanner 3.68.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
sentence-transformers 5.5.1 requires transformers<6.0.0,>=4.41.0, but you have transformers 4.35.2 which is incompatible.
googleapis-common-protos 1.75.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
proto-plus 1.28.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-translate 3.26.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 3.20.0 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.6.1 which is incompatible.
google-cloud-functions 1.23.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-firestore 2.27.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-appengine-logging 1.10.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-trace 1.19.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
google-cloud-logging 3.16.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 3.20.0 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
google-cloud-iam 2.23.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
tensorflow-metadata 1.21.0 requires protobuf>=4.25.2; python_version >= "3.11", but you have protobuf 3.20.0 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
google-cloud-dataplex 2.20.0 requires protobuf<8.0.0,>=4.25.8, but you have protobuf 3.20.0 which is incompatible.
Successfully installed datasets-2.21.0 fsspec-2024.6.1 huggingface-hub-0.36.2 jsonlines-2.0.0 lightning-utilities-0.15.3 numpy-1.26.4 protobuf-3.20.0 pytorch-lightning-1.9.5 tokenizers-0.15.2 torchmetrics-1.9.0 transformers-4.35.2

In [4]:
!pwd

/content/AlignScore

In [1]:
!ls

AlignScore  sample_data

In [2]:
# uninstalling the present weight and biases library
!pip uninstall -y wandb

Found existing installation: wandb 0.27.2
Uninstalling wandb-0.27.2:
  Successfully uninstalled wandb-0.27.2

In [3]:
# installing required weight and biases library version
!pip install wandb==0.16.6

Collecting wandb==0.16.6
  Downloading wandb-0.16.6-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: Click!=8.0.0,>=7.1 in /usr/local/lib/python3.12/dist-packages (from wandb==0.16.6) (8.4.1)
Requirement already satisfied: GitPython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.16.6) (3.1.50)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.16.6) (2.32.4)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.16.6) (5.9.5)
Requirement already satisfied: sentry-sdk>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.16.6) (2.62.0)
Collecting docker-pycreds>=0.4.0 (from wandb==0.16.6)
  Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from wandb==0.16.6) (6.0.3)
Collecting setproctitle (from wandb==0.16.6)
  Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from wandb==0.16.6) (75.2.0)
Collecting appdirs>=1.4.3 (from wandb==0.16.6)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: protobuf!=4.21.0,<5,>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from wandb==0.16.6) (3.20.0)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from docker-pycreds>=0.4.0->wandb==0.16.6) (1.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from GitPython!=3.1.29,>=1.0.0->wandb==0.16.6) (4.0.12)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.16.6) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.16.6) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.16.6) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb==0.16.6) (2026.5.20)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->GitPython!=3.1.29,>=1.0.0->wandb==0.16.6) (5.0.3)
Downloading wandb-0.16.6-py3-none-any.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 27.7 MB/s eta 0:00:00
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading docker_pycreds-0.4.0-py2.py3-none-any.whl (9.0 kB)
Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (32 kB)
Installing collected packages: appdirs, setproctitle, docker-pycreds, wandb
Successfully installed appdirs-1.4.4 docker-pycreds-0.4.0 setproctitle-1.3.7 wandb-0.16.6

In [4]:
# appedning the path for the alignscore in src
import sys
sys.path.append("/content/AlignScore/src")

# chceking the alignscore library
import alignscore
print("alignscore imported")

/usr/local/lib/python3.12/dist-packages/transformers/utils/generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.12/dist-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
/usr/local/lib/python3.12/dist-packages/transformers/utils/generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

alignscore imported

In [5]:
from alignscore import AlignScore
print("AlignScore class imported")

AlignScore class imported

In [6]:
# Alignscore model using the model roberta-base model with evaluation mode = nli_sp
scorer = AlignScore(
    model='roberta-base',
    batch_size=4,
    device='cuda:0',
    ckpt_path='/content/AlignScore/ckpt/AlignScore-base.ckpt',
    evaluation_mode='nli_sp'
)

print("Model loaded")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.7.7 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file AlignScore/ckpt/AlignScore-base.ckpt`
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/pytorch_lightning/core/saving.py:255: UserWarning: Found keys that are not in the model state dict but in the checkpoint: ['base_model.embeddings.position_ids']
  rank_zero_warn(

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Model loaded

In [7]:
# for tokenizer
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [8]:
# checking for correct small legal example
contexts = ["The court held that the contract was valid and enforceable."]
claims = ["The contract was valid."]

score = scorer.score(contexts=contexts, claims=claims)

print("\nScore --> ", score)

Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.20it/s]

Score -->  [0.9379122257232666]

In [9]:
# hallucinated example
contexts = ["The court held that the contract was valid and enforceable."]
claims = ["The contract was invalid."]

score = scorer.score(contexts=contexts, claims=claims)
print("\nHallucinted Example Score --> ", score)
#

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 15.19it/s]

Hallucinted Example Score -->  [0.0006623139488510787]

# Legal Model

In [10]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (2.21.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.7.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets) (2024.6.1)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from datasets) (3.14.1)
Requirement already satisfied: huggingface-hub>=0.21.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets) (4.15.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->datasets) (1.24.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.21.2->datasets) (1.5.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.5.20)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [11]:
from datasets import load_dataset

In [20]:
# downloading the ContractNLI dataset from huggingface
# two configuration of this dataset contractnli_a and contractnli_b and
# using the contractnli_a and then use the contractnli_b for evaluation
from datasets import load_dataset

contract_nli = load_dataset(
    "kiddothe2b/contract-nli",
    "contractnli_a",
    split="train",
    streaming=True
)

example = next(iter(contract_nli))
print(example)
# columns in the dataset
print(example.keys())

{'premise': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to: 2.3.1  Any other party with the Discloser’s prior written consent; and 2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:', 'hypothesis': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.", 'label': 2}
dict_keys(['premise', 'hypothesis', 'label'])

In [24]:
# BillSum dataset --> legal document summarization dataset having text and summary
billsum = load_dataset(
    "billsum",
    split="train",
    streaming=True
)
example = next(iter(billsum))
print(example)
print(example.keys())

{'text': "SECTION 1. LIABILITY OF BUSINESS ENTITIES PROVIDING USE OF FACILITIES \n              TO NONPROFIT ORGANIZATIONS.\n\n    (a) Definitions.--In this section:\n            (1) Business entity.--The term ``business entity'' means a \n        firm, corporation, association, partnership, consortium, joint \n        venture, or other form of enterprise.\n            (2) Facility.--The term ``facility'' means any real \n        property, including any building, improvement, or appurtenance.\n            (3) Gross negligence.--The term ``gross negligence'' means \n        voluntary and conscious conduct by a person with knowledge (at \n        the time of the conduct) that the conduct is likely to be \n        harmful to the health or well-being of another person.\n            (4) Intentional misconduct.--The term ``intentional \n        misconduct'' means conduct by a person with knowledge (at the \n        time of the conduct) that the conduct is harmful to the health \n        or well-being of another person.\n            (5) Nonprofit organization.--The term ``nonprofit \n        organization'' means--\n                    (A) any organization described in section 501(c)(3) \n                of the Internal Revenue Code of 1986 and exempt from \n                tax under section 501(a) of such Code; or\n                    (B) any not-for-profit organization organized and \n                conducted for public benefit and operated primarily for \n                charitable, civic, educational, religious, welfare, or \n                health purposes.\n            (6) State.--The term ``State'' means each of the several \n        States, the District of Columbia, the Commonwealth of Puerto \n        Rico, the Virgin Islands, Guam, American Samoa, the Northern \n        Mariana Islands, any other territory or possession of the \n        United States, or any political subdivision of any such State, \n        territory, or possession.\n    (b) Limitation on Liability.--\n            (1) In general.--Subject to subsection (c), a business \n        entity shall not be subject to civil liability relating to any \n        injury or death occurring at a facility of the business entity \n        in connection with a use of such facility by a nonprofit \n        organization if--\n                    (A) the use occurs outside of the scope of business \n                of the business entity;\n                    (B) such injury or death occurs during a period \n                that such facility is used by the nonprofit \n                organization; and\n                    (C) the business entity authorized the use of such \n                facility by the nonprofit organization.\n            (2) Application.--This subsection shall apply--\n                    (A) with respect to civil liability under Federal \n                and State law; and\n                    (B) regardless of whether a nonprofit organization \n                pays for the use of a facility.\n    (c) Exception for Liability.--Subsection (b) shall not apply to an \ninjury or death that results from an act or omission of a business \nentity that constitutes gross negligence or intentional misconduct, \nincluding any misconduct that--\n            (1) constitutes a crime of violence (as that term is \n        defined in section 16 of title 18, United States Code) or act \n        of international terrorism (as that term is defined in section \n        2331 of title 18) for which the defendant has been convicted in \n        any court;\n            (2) constitutes a hate crime (as that term is used in the \n        Hate Crime Statistics Act (28 U.S.C. 534 note));\n            (3) involves a sexual offense, as defined by applicable \n        State law, for which the defendant has been convicted in any \n        court; or\n            (4) involves misconduct for which the defendant has been \n        found to have violated a Federal or State civil rights law.\n    (d) Superseding Provision.--\n            (1) In general.--Subject to paragraph (2) and subsection \n        (e), this Act preempts the laws of any State to the extent that \n        such laws are inconsistent with this Act, except that this Act \n        shall not preempt any State law that provides additional \n        protection from liability for a business entity for an injury \n        or death with respect to which conditions under subparagraphs \n        (A) through (C) of subsection (b)(1) apply.\n            (2) Limitation.--Nothing in this Act shall be construed to \n        supersede any Federal or State health or safety law.\n    (e) Election of State Regarding Nonapplicability.--This Act shall \nnot apply to any civil action in a State court against a business \nentity in which all parties are citizens of the State if such State \nenacts a statute--\n            (1) citing the authority of this subsection;\n            (2) declaring the election of such State that this Act \n        shall not apply to such civil action in the State; and\n            (3) containing no other provision.", 'summary': "Shields a business entity from civil liability relating to any injury or death occurring at a facility of that entity in connection with a use of such facility by a nonprofit organization if: (1) the use occurs outside the scope of business of the business entity; (2) such injury or death occurs during a period that such facility is used by such organization; and (3) the business entity authorized the use of such facility by the organization. \nMakes this Act inapplicable to an injury or death that results from an act or omission of a business entity that constitutes gross negligence or intentional misconduct, including misconduct that: (1) constitutes a hate crime or a crime of violence or act of international terrorism for which the defendant has been convicted in any court; or (2) involves a sexual offense for which the defendant has been convicted in any court or misconduct for which the defendant has been found to have violated a Federal or State civil rights law. \nPreempts State laws to the extent that such laws are inconsistent with this Act, except State law that provides additional protection from liability.  Specifies that this Act shall not be construed to supersede any Federal or State health or safety law. \nMakes this Act inapplicable to any civil action in a State court against a business entity in which all parties are citizens of the State if such State, citing this Act's authority and containing no other provision, enacts a statute declaring the State's election that this Act shall not apply to such action in the State.", 'title': 'A bill to limit the civil liability of business entities providing use of facilities to nonprofit organizations.'}
dict_keys(['text', 'summary', 'title'])

In [23]:
# CaseHOLD dataset --> Case Holdings on Long Decisions
casehold = load_dataset(
    "lex_glue",
    "case_hold",
    split="train",
    streaming=True
)
example = next(iter(casehold))
print(example)
print(example.keys())

Downloading readme:   0%|          | 0.00/34.1k [00:00<?, ?B/s]

{'context': "Drapeau’s cohorts, the cohort would be a “victim” of making the bomb. Further, firebombs are inherently dangerous. There is no peaceful purpose for making a bomb. Felony offenses that involve explosives qualify as “violent crimes” for purposes of enhancing the sentences of career offenders. See 18 U.S.C. § 924(e)(2)(B)(ii) (defining a “violent felony” as: “any crime punishable by imprisonment for a term exceeding one year ... that ... involves use of explosives”). Courts have found possession of a'bomb to be a crime of violence based on the lack of a nonviolent purpose for a bomb and the fact that, by its very nature, there is a substantial risk that the bomb would be used against the person or property of another. See United States v. Newman, 125 F.3d 863 (10th Cir.1997) (unpublished) (<HOLDING>); United States v. Dodge, 846 F.Supp. 181,", 'endings': ['holding that possession of a pipe bomb is a crime of violence for purposes of 18 usc  3142f1', 'holding that bank robbery by force and violence or intimidation under 18 usc  2113a is a crime of violence', 'holding that sexual assault of a child qualified as crime of violence under 18 usc  16', 'holding for the purposes of 18 usc  924e that being a felon in possession of a firearm is not a violent felony as defined in 18 usc  924e2b', 'holding that a court must only look to the statutory definition not the underlying circumstances of the crime to determine whether a given offense is by its nature a crime of violence for purposes of 18 usc  16'], 'label': 0}
dict_keys(['context', 'endings', 'label'])

In [30]:
# Now aligning the dataset in the alignscore format --> contexts and claims
# billsum
billsum_example = next(iter(billsum))

context = billsum_example["text"]
claim = billsum_example["summary"]

print("Context length:", len(context))
print("Claim length:", len(claim))
print("\nClaim:\n", claim)

score = scorer.score(
    contexts=[context],
    claims=[claim]
)

print("\nBillSum AlignScore:", score)

Context length: 5026
Claim length: 1561

Claim:
 Shields a business entity from civil liability relating to any injury or death occurring at a facility of that entity in connection with a use of such facility by a nonprofit organization if: (1) the use occurs outside the scope of business of the business entity; (2) such injury or death occurs during a period that such facility is used by such organization; and (3) the business entity authorized the use of such facility by the organization.
Makes this Act inapplicable to an injury or death that results from an act or omission of a business entity that constitutes gross negligence or intentional misconduct, including misconduct that: (1) constitutes a hate crime or a crime of violence or act of international terrorism for which the defendant has been convicted in any court; or (2) involves a sexual offense for which the defendant has been convicted in any court or misconduct for which the defendant has been found to have violated a Federal or State civil rights law.
Preempts State laws to the extent that such laws are inconsistent with this Act, except State law that provides additional protection from liability.  Specifies that this Act shall not be construed to supersede any Federal or State health or safety law.
Makes this Act inapplicable to any civil action in a State court against a business entity in which all parties are citizens of the State if such State, citing this Act's authority and containing no other provision, enacts a statute declaring the State's election that this Act shall not apply to such action in the State.

Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.20it/s]

BillSum AlignScore: [0.6652727127075195]

In [31]:
# for CaseHOLD
casehold_example = next(iter(casehold))

context = casehold_example["context"]
correct_claim = casehold_example["endings"][casehold_example["label"]]

print("Context:\n", context[:1000])
print("\nCorrect claim:\n", correct_claim)

score = scorer.score(
    contexts=[context],
    claims=[correct_claim]
)

print("\nCaseHOLD correct claim score:", score)

Context:
 Drapeau’s cohorts, the cohort would be a “victim” of making the bomb. Further, firebombs are inherently dangerous. There is no peaceful purpose for making a bomb. Felony offenses that involve explosives qualify as “violent crimes” for purposes of enhancing the sentences of career offenders. See 18 U.S.C. § 924(e)(2)(B)(ii) (defining a “violent felony” as: “any crime punishable by imprisonment for a term exceeding one year ... that ... involves use of explosives”). Courts have found possession of a'bomb to be a crime of violence based on the lack of a nonviolent purpose for a bomb and the fact that, by its very nature, there is a substantial risk that the bomb would be used against the person or property of another. See United States v. Newman, 125 F.3d 863 (10th Cir.1997) (unpublished) (<HOLDING>); United States v. Dodge, 846 F.Supp. 181,

Correct claim:
 holding that possession of a pipe bomb is a crime of violence for purposes of 18 usc  3142f1

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 14.74it/s]

CaseHOLD correct claim score: [0.09620422124862671]

In [32]:
# for contractNLI
contract_example = next(iter(contract_nli))

context = contract_example["premise"]
claim = contract_example["hypothesis"]

print("Context:\n", context[:1000])
print("\nClaim:\n", claim)

score = scorer.score(
    contexts=[context],
    claims=[claim]
)

print("\nContractNLI AlignScore:", score)

Context:
 2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to: 2.3.1  Any other party with the Discloser’s prior written consent; and 2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:

Claim:
 Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information.

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 13.56it/s]

ContractNLI AlignScore: [0.007603729143738747]

In [33]:
# creating the dataset extractors for each dataset
from itertools import islice

def get_billsum_pairs(dataset, n=5):
    pairs = []
    for ex in islice(dataset, n):
        pairs.append({
            "dataset": "BillSum",
            "context": ex["text"],
            "claim": ex["summary"]
        })
    return pairs


def get_casehold_pairs(dataset, n=5):
    pairs = []
    for ex in islice(dataset, n):
        correct_claim = ex["endings"][ex["label"]]
        pairs.append({
            "dataset": "CaseHOLD",
            "context": ex["context"],
            "claim": correct_claim
        })
    return pairs


def get_contractnli_pairs(dataset, n=5):
    pairs = []
    for ex in islice(dataset, n):
        pairs.append({
            "dataset": "ContractNLI",
            "context": ex["premise"],
            "claim": ex["hypothesis"]
        })
    return pairs

In [38]:
# combining the dataset in the one dataset
all_pairs = []

all_pairs.extend(get_contractnli_pairs(contract_nli, n=500))
all_pairs.extend(get_billsum_pairs(billsum, n=500))
all_pairs.extend(get_casehold_pairs(casehold, n=500))

print("Total examples:", len(all_pairs))
print("Printing the first example")
print(all_pairs[0])

Total examples: 1500
Printing the first example
{'dataset': 'ContractNLI', 'context': '2.3 Provided that the Recipient has a written agreement with the following persons or entities requiring them to treat the Confidential Information in accordance with this Agreement, the Recipient may disclose the Confidential Information to: 2.3.1  Any other party with the Discloser’s prior written consent; and 2.3.2 the Recipient’s employees, officials, representatives and agents who have a strict need to know the contents of the Confidential Information, and employees, officials, representatives and agents of any legal entity that it controls, controls it, or with which it is under common control, who have a similar need to know the contents of the Confidential Information, provided that, for these purposes a controlled legal entity means:', 'claim': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information."}

In [37]:
# Running the baseline RoBERTa AlignScore
results = []

for item in all_pairs:
    score = scorer.score(
        contexts=[item["context"]],
        claims=[item["claim"]]
    )[0]

    results.append({
        "dataset": item["dataset"],
        "model": "RoBERTa AlignScore baseline",
        "alignscore": score,
        "claim": item["claim"][:300]
    })

print(results)

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 14.79it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 16.80it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 16.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 15.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.47it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 15.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.17it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.45it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.29it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.10it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.94it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.66it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.12it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.72it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.09it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.37it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.44it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.42it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.81it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.17it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.54it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.81it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.11it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 16.11it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 24.06it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.53it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.68it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.46it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.49it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.25it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.96it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.00it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.32it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.13it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.26it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.77it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.80it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.55it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.14it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.53it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.83it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.55it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.16it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.69it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.28it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.43it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.48it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.72it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.63it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.72it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.90it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.72it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.21it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.05it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.75it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.16it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.93it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.68it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.25it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.44it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.16it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.89it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.18it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.39it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.75it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.80it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  6.49it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.13it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.35it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.29it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.99it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.04it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.50it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.54it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.16it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.63it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.10it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.85it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.25it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.28it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.97it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.35it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.68it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.91it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.20it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.83it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.19it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.18it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.02it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.13it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.64it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.00it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.88it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.99it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.87it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.74it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.47it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.81it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.47it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.31it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.90it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.48it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.21it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.40it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.55it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.92it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.27it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.79it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.54it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.08it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.85it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.02it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.98it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.67it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.35it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.96it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.81it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.94it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.69it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.87it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.91it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.77it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.00it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.97it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.69it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.88it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.24it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.24it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.30it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.93it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.91it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.17it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.40it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.24it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.37it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.05it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.75it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.41it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.51it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.10it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.12it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.53it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.95it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.19it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.19it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.42it/s]

[{'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.007603729143738747, 'claim': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.3993086516857147, 'claim': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.9584909081459045, 'claim': 'Agreement shall not grant Receiving Party any right to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.12430699914693832, 'claim': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0020760504994541407, 'claim': 'Confidential Information shall only include technical information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0352054201066494, 'claim': 'All Confidential Information shall be expressly identified by the Disclosing Party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.9765961170196533, 'claim': 'Some obligations of Agreement may survive termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.8265884518623352, 'claim': 'Receiving Party may independently develop information similar to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.023414291441440582, 'claim': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.3387497663497925, 'claim': 'Confidential Information may include verbally conveyed information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.02728108875453472, 'claim': "Receiving Party shall not solicit some of Disclosing Party's representatives."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0986533835530281, 'claim': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.05297344550490379, 'claim': 'Receiving Party may create a copy of some Confidential Information in some circumstances.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0663595125079155, 'claim': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.8177224397659302, 'claim': 'Receiving Party may acquire information similar to Confidential Information from a third party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.9272257685661316, 'claim': "Receiving Party may share some Confidential Information with some of Receiving Party's employees."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.12038451433181763, 'claim': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.006221717223525047, 'claim': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.008177857846021652, 'claim': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.17808260023593903, 'claim': 'Agreement shall not grant Receiving Party any right to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0022235633805394173, 'claim': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.001321619376540184, 'claim': 'Confidential Information shall only include technical information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.007247876841574907, 'claim': 'All Confidential Information shall be expressly identified by the Disclosing Party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.414264976978302, 'claim': 'Some obligations of Agreement may survive termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.8265884518623352, 'claim': 'Receiving Party may independently develop information similar to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.007973515428602695, 'claim': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.002140989527106285, 'claim': 'Confidential Information may include verbally conveyed information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.011914306320250034, 'claim': "Receiving Party shall not solicit some of Disclosing Party's representatives."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0062050726264715195, 'claim': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.17009080946445465, 'claim': 'Receiving Party may create a copy of some Confidential Information in some circumstances.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.3559264540672302, 'claim': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.842785120010376, 'claim': 'Receiving Party may acquire information similar to Confidential Information from a third party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.053196679800748825, 'claim': "Receiving Party may share some Confidential Information with some of Receiving Party's employees."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.5267670750617981, 'claim': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.011419283226132393, 'claim': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.11325668543577194, 'claim': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.020919684320688248, 'claim': 'Agreement shall not grant Receiving Party any right to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.050001032650470734, 'claim': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0074730669148266315, 'claim': 'Confidential Information shall only include technical information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.31340348720550537, 'claim': 'All Confidential Information shall be expressly identified by the Disclosing Party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.9345719218254089, 'claim': 'Some obligations of Agreement may survive termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.04030342027544975, 'claim': 'Receiving Party may independently develop information similar to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.09026269614696503, 'claim': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.07096090167760849, 'claim': 'Confidential Information may include verbally conveyed information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.04953458532691002, 'claim': "Receiving Party shall not solicit some of Disclosing Party's representatives."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.005245220847427845, 'claim': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.003781417151913047, 'claim': 'Receiving Party may create a copy of some Confidential Information in some circumstances.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.7258638739585876, 'claim': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.605067789554596, 'claim': 'Receiving Party may acquire information similar to Confidential Information from a third party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.4744109511375427, 'claim': "Receiving Party may share some Confidential Information with some of Receiving Party's employees."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.8099924325942993, 'claim': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.011419283226132393, 'claim': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.01165375392884016, 'claim': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.7913078665733337, 'claim': 'Agreement shall not grant Receiving Party any right to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.9363489747047424, 'claim': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0010933828307315707, 'claim': 'Confidential Information shall only include technical information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.04263434186577797, 'claim': 'All Confidential Information shall be expressly identified by the Disclosing Party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.014374232850968838, 'claim': 'Some obligations of Agreement may survive termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.793475329875946, 'claim': 'Receiving Party may independently develop information similar to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.07132774591445923, 'claim': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0022673807106912136, 'claim': 'Confidential Information may include verbally conveyed information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.04953458532691002, 'claim': "Receiving Party shall not solicit some of Disclosing Party's representatives."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0062050726264715195, 'claim': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.003781417151913047, 'claim': 'Receiving Party may create a copy of some Confidential Information in some circumstances.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.6824588179588318, 'claim': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.11680483818054199, 'claim': "Receiving Party may share some Confidential Information with some of Receiving Party's employees."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.9409541487693787, 'claim': 'Receiving Party shall not use any Confidential Information for any purpose other than the purposes stated in Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.020530177280306816, 'claim': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.8608759641647339, 'claim': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.799396812915802, 'claim': 'Agreement shall not grant Receiving Party any right to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.9363489747047424, 'claim': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.001973143545910716, 'claim': 'Confidential Information shall only include technical information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.15002143383026123, 'claim': 'All Confidential Information shall be expressly identified by the Disclosing Party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.015917684882879257, 'claim': 'Receiving Party may independently develop information similar to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.03643128275871277, 'claim': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.009232953190803528, 'claim': 'Confidential Information may include verbally conveyed information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.01004792284220457, 'claim': "Receiving Party shall not solicit some of Disclosing Party's representatives."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.00904014427214861, 'claim': 'Receiving Party may create a copy of some Confidential Information in some circumstances.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.012099514715373516, 'claim': 'Receiving Party shall notify Disclosing Party in case Receiving Party is required by law, regulation or judicial process to disclose any Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0170268714427948, 'claim': 'Receiving Party may acquire information similar to Confidential Information from a third party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.012175253592431545, 'claim': "Receiving Party may share some Confidential Information with some of Receiving Party's employees."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.09193740785121918, 'claim': "Receiving Party shall not reverse engineer any objects which embody Disclosing Party's Confidential Information."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.054746199399232864, 'claim': 'Receiving Party shall destroy or return some Confidential Information upon the termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.16697709262371063, 'claim': 'Agreement shall not grant Receiving Party any right to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.9363489747047424, 'claim': 'Receiving Party shall not disclose the fact that Agreement was agreed or negotiated.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0012983273481950164, 'claim': 'Confidential Information shall only include technical information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.15002143383026123, 'claim': 'All Confidential Information shall be expressly identified by the Disclosing Party.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.24559873342514038, 'claim': 'Some obligations of Agreement may survive termination of Agreement.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.8712456822395325, 'claim': 'Receiving Party may independently develop information similar to Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.04198763519525528, 'claim': 'Receiving Party may retain some Confidential Information even after the return or destruction of Confidential Information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.11216481029987335, 'claim': 'Confidential Information may include verbally conveyed information.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.21388882398605347, 'claim': "Receiving Party shall not solicit some of Disclosing Party's representatives."}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.0030133253894746304, 'claim': 'Receiving Party may share some Confidential Information with some third-parties (including consultants, agents and professional advisors).'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', 'alignscore': 0.10421956330537796, 'claim': 'Receiving Party may create a copy of some Confidential Information in some circumstances.'}, {'dataset': 'ContractNLI', 'model': 'RoBERTa AlignScore baseline', '

In [39]:
import pandas as pd

df_results = pd.DataFrame(results)
df_results

,dataset,model,alignscore,claim
0,ContractNLI,RoBERTa AlignScore baseline,0.007604,Receiving Party shall not reverse engineer any...
1,ContractNLI,RoBERTa AlignScore baseline,0.399309,Receiving Party shall destroy or return some C...
2,ContractNLI,RoBERTa AlignScore baseline,0.958491,Agreement shall not grant Receiving Party any ...
3,ContractNLI,RoBERTa AlignScore baseline,0.124307,Receiving Party shall not disclose the fact th...
4,ContractNLI,RoBERTa AlignScore baseline,0.002076,Confidential Information shall only include te...
...,...,...,...,...
1495,CaseHOLD,RoBERTa AlignScore baseline,0.313640,holding that a count of 18 usc 1957 money lau...
1496,CaseHOLD,RoBERTa AlignScore baseline,0.744077,holding that claims not raised in an appellant...
1497,CaseHOLD,RoBERTa AlignScore baseline,0.521878,holding as a matter of first impression that t...
1498,CaseHOLD,RoBERTa AlignScore baseline,0.009483,holding that congress may even have been unsuc...
1499,CaseHOLD,RoBERTa AlignScore baseline,0.036479,holding ports authority was not an employer su...

In [40]:
df_results.to_csv("roberta_baseline_alignscore_results.csv", index=False)

* RoBERTa baseline = use existing AlignScore checkpoint
* LegalBERT / LegalRoBERTa = need modified model loading or fine-tuned checkpoint

In [41]:
# LegalBERT
from alignscore import AlignScore

legalbert_scorer = AlignScore(
    model='nlpaueb/legal-bert-base-uncased',
    batch_size=4,
    device='cuda:0',
    ckpt_path='/content/AlignScore/ckpt/AlignScore-base.ckpt',
    evaluation_mode='nli_sp'
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.7.7 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file AlignScore/ckpt/AlignScore-base.ckpt`
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.12/dist-packages/pytorch_lightning/core/saving.py:255: UserWarning: Found keys that are not in the model state dict but in the checkpoint: ['base_model.embeddings.position_ids']
  rank_zero_warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [42]:
# LegalRoBERTa
legalroberta_scorer = AlignScore(
    model='saibo/legal-roberta-base',
    batch_size=4,
    device='cuda:0',
    ckpt_path='/content/AlignScore/ckpt/AlignScore-base.ckpt',
    evaluation_mode='nli_sp'
)

config.json:   0%|          | 0.00/578 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at saibo/legal-roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.7.7 to v1.9.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file AlignScore/ckpt/AlignScore-base.ckpt`
Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

For whole dataset present in Dataset

In [52]:
# now creating the training data from Dataset-1 ContractNLI
contract_train_pairs = []

for ex in islice(contract_nli, 100):
    contract_train_pairs.append({
        "context": ex["premise"],
        "claim": ex["hypothesis"],
        "label": ex["label"]
    })

print("Total pairs:", len(contract_train_pairs))
import pandas as pd

df_contract = pd.DataFrame(contract_train_pairs)
df_contract.sample(10)

Total pairs: 100

,context,claim,label
86,5. No Further Rights All Confidential Informat...,All Confidential Information shall be expressl...,2
24,The Recipient shall not be precluded from disc...,Receiving Party may independently develop info...,2
12,The Recipient will not copy or reproduce the C...,Receiving Party may create a copy of some Conf...,1
94,III. LEGALLY REQUIRED DISCLOSURES: If Receivin...,Receiving Party shall notify Disclosing Party ...,1
60,Mentor shall not use any Confidential Informat...,Confidential Information may include verbally ...,2
54,"The existence of any business negotiations, di...",Receiving Party shall not disclose the fact th...,1
15,2.3 Provided that the Recipient has a written ...,Receiving Party may share some Confidential In...,1
81,IV. NO REVERSE ENGINEERING; WORK PRODUCT: Rece...,Receiving Party shall not reverse engineer any...,1
96,5. No Further Rights All Confidential Informat...,Receiving Party may share some Confidential In...,2
21,“Confidential Information” means any Idea disc...,Confidential Information shall only include te...,0

In [53]:
df_contract.to_csv("contract_pairs.csv", index=False)

In [54]:
billsum_pairs = []

for ex in islice(billsum, 100):
    billsum_pairs.append({
        "dataset": "BillSum",
        "context": ex["text"],
        "claim": ex["summary"],
        "label": "summary"
    })

df_billsum = pd.DataFrame(billsum_pairs)
df_billsum.sample(10)

,dataset,context,claim,label
70,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,Safety Net Extension Act - Amends the Temporar...,summary
82,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,Nurses for Under-Resourced Schools Everywhere ...,summary
84,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,George C. Marshall Commemorative Coin Act - Di...,summary
85,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,Church Insurance Protection Act - Expresses th...,summary
33,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,Rio Grande Del Norte National Conservation Are...,summary
2,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,Jackie Robinson Commemorative Coin Act - Direc...,summary
77,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,Timely Repatriation Act This bill directs the...,summary
3,BillSum,SECTION 1. NONRECOGNITION OF GAIN WHERE ROLLOV...,Amends the Internal Revenue Code to provide (t...,summary
40,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,Emergency Petroleum Supply Act - Amends the En...,summary
98,BillSum,SECTION 1. SHORT TITLE.\n\n This Act may be...,Medical Laboratory Personnel Shortage Act of 2...,summary

In [55]:
df_billsum.to_csv("billsum_pairs.csv", index=False)

In [56]:
casehold_pairs = []

for ex in islice(casehold, 100):
    correct_claim = ex["endings"][ex["label"]]

    casehold_pairs.append({
        "dataset": "CaseHOLD",
        "context": ex["context"],
        "claim": correct_claim,
        "label": ex["label"]
    })

df_casehold = pd.DataFrame(casehold_pairs)
df_casehold.sample(10)

,dataset,context,claim,label
49,CaseHOLD,"Houdek v. Mobil Oil Corp., 879 P.2d 417, 425 (...",holding the dismissed defendant was not preclu...,2
64,CaseHOLD,applies to the bankruptcy court’s severance of...,recognizing that the party can instead file a ...,4
73,CaseHOLD,"limit, modify, or eliminate altogether. See, e...",holding that an indian tribe is subject to sui...,4
24,CaseHOLD,"any physician that described her as obese, muc...",recognizing aljs credibility assessment is ent...,3
28,CaseHOLD,"as a special education teacher, and commencing...",holding that reinstatement is prospective even...,4
26,CaseHOLD,in the record of any possible medical treatmen...,holding that plaintiffs failure to prove deced...,1
0,CaseHOLD,"Drapeau’s cohorts, the cohort would be a “vict...",holding that possession of a pipe bomb is a cr...,0
39,CaseHOLD,address the precise language of the agreement....,holding that arbitral award of 10 interest to ...,2
36,CaseHOLD,"States Dist. Court, 407 U.S. 297, 313, 92 S.Ct...",holding that government employers may conduct ...,4
21,CaseHOLD,"Inc., 415 U.S. 125, 127, 94 S.Ct. 1002, 39 L.E...",holding that a counterclaim which appears as ...,4

In [57]:
df_casehold.to_csv("casehold_pairs.csv", index=False)

In [75]:
# combining the whole dataset into one dataframe
df_all = pd.concat(
    [df_contract, df_billsum, df_casehold],
    ignore_index=True
)
df_all.sample(10)

,context,claim,label,dataset
89,5. No Further Rights All Confidential Informat...,Receiving Party may retain some Confidential I...,2,NaN
47,(a) In the event that any governmental authori...,Receiving Party shall notify Disclosing Party ...,1,NaN
149,"SECTION 1. DEFINITIONS.\n\n In this Act, th...",Authorizes the Secretary of the Interior to en...,summary,BillSum
195,SECTION 1. SHORT TITLE.\n\n This Act may be...,Water Supply Permitting Coordination Act (Sec...,summary,BillSum
189,SECTION 1. COMMISSION.\n\n This Act may be ...,Protect our Kids Act of 2011 - Establishes the...,summary,BillSum
234,"part: ""If no objections have been timely filed...",holding that walsh was entitled to postjudgmen...,1,CaseHOLD
276,indicated a willingness to consider additional...,recognizing the supreme courts subtle yet cruc...,4,CaseHOLD
260,"the “quick intervention” of Dr. Kasozi, “most ...",holding that the ijs or bias credibility deter...,1,CaseHOLD
232,official would understand that what he is doin...,holding a gun to the head of a child and threa...,4,CaseHOLD
184,SECTION 1. SHORT TITLE.\n\n This Act may be...,George C. Marshall Commemorative Coin Act - Di...,summary,BillSum

In [76]:
# size
df_all.size

1200

In [83]:
df_all.shape

(300, 4)

In [77]:
# unique values from tge dataset colujmns
df_all['dataset'].value_counts()

dataset
BillSum     100
CaseHOLD    100
Name: count, dtype: int64

In [78]:
# checking NaN values in df_all
df_all.isna().sum()

context      0
claim        0
label        0
dataset    100
dtype: int64

In [79]:
# mapping the NaN value in dataset column of df_all into Contract
df_all['dataset'] = df_all['dataset'].fillna('Contract')

In [80]:
df_all['dataset'].value_counts()

dataset
Contract    100
BillSum     100
CaseHOLD    100
Name: count, dtype: int64

In [81]:
df_all.sample(10)

,context,claim,label,dataset
242,unique facts and circumstances of each case” t...,holding district courts finding of consent was...,3,CaseHOLD
203,They also rely on Oswego Laborers’ Local 214 P...,holding that plaintiff stated a 349 claim whe...,0,CaseHOLD
120,SECTION 1. SHORT TITLE.\n\n This Act may be...,Protect and Preserve International Cultural Pr...,summary,BillSum
188,"s, Amendments, Amendments Between the \nHouses...",Earmark Elimination Act of 2018 This bill est...,summary,BillSum
61,Mentor shall not disclose any Confidential Inf...,Receiving Party shall not solicit some of Disc...,2,Contract
104,SECTION 1. SHORT TITLE.\n\n This Act may be...,Native American Energy Act - (Sec. 3) Amends t...,summary,BillSum
82,5. No Further Rights All Confidential Informat...,Receiving Party shall destroy or return some C...,2,Contract
12,The Recipient will not copy or reproduce the C...,Receiving Party may create a copy of some Conf...,1,Contract
142,SECTION 1. COMPUTER TECHNOLOGY AND EQUIPMENT A...,"Amends the Internal Revenue Code, with respect...",summary,BillSum
81,IV. NO REVERSE ENGINEERING; WORK PRODUCT: Rece...,Receiving Party shall not reverse engineer any...,1,Contract

In [82]:
df_all.to_csv("legal_datasets_combined.csv", index=False)

Now we'll run different models on it

In [84]:
# Baseline model --> RoBERTa
baseline_results = []

for i, row in df_all.iterrows():
    score = scorer.score(
        contexts=[row["context"]],
        claims=[row["claim"]]
    )[0]

    baseline_results.append({
        "dataset": row["dataset"],
        "model": "RoBERTa-AlignScore",
        "alignscore": score,
        "claim": row["claim"][:300]
    })

    if i % 10 == 0:
        print(f"Done {i}/{len(df_all)}")

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 10.56it/s]

Done 0/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 14.84it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 15.18it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.11it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 18.60it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 23.80it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.11it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.29it/s]

Done 10/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.79it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.87it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.92it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.30it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.75it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.96it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.10it/s]

Done 20/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.30it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.92it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.69it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.26it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.45it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.72it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.63it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.04it/s]

Done 30/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.85it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.63it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.47it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.58it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.54it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.09it/s]

Done 40/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.35it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.43it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.61it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.89it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.31it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.09it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.59it/s]

Done 50/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.01it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.03it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.54it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.09it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.61it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.11it/s]

Done 60/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.69it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.08it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.71it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.88it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.02it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.68it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.04it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.88it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.02it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.88it/s]

Done 70/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.02it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.25it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.53it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.58it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.70it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.68it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]

Done 80/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.21it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.54it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.89it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.64it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.67it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.83it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.26it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.76it/s]

Done 90/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.72it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.35it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.70it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.16it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.06it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.21it/s]

Done 100/300

Evaluating: 100%|██████████| 1/1 [00:03<00:00,  3.59s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.97it/s]
Evaluating: 100%|██████████| 1/1 [00:11<00:00, 11.46s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.56it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.34s/it]
Evaluating: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it]
Evaluating: 100%|██████████| 1/1 [00:02<00:00,  2.49s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.53it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.39it/s]

Done 110/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00,  9.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.27it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.98s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.30it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.64s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.25it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.36it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.19it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.83s/it]

Done 120/300

Evaluating: 100%|██████████| 1/1 [00:03<00:00,  3.10s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.89it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.41s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.91it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.16it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.62s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.97it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.32it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.35it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  5.21it/s]

Done 130/300

Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.24s/it]
Evaluating: 100%|██████████| 1/1 [00:02<00:00,  2.23s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.28it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.02it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.87it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.34it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.36s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.03it/s]

Done 140/300

Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.33s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  9.79it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.91it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  4.89it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.87s/it]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.19s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.37it/s]
Evaluating: 100%|██████████| 1/1 [00:04<00:00,  4.76s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.58it/s]

Done 150/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.61it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  4.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.70it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.18it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.12it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.02it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  5.12it/s]
Evaluating: 100%|██████████| 1/1 [00:03<00:00,  3.30s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  7.07it/s]

Done 160/300

Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.75s/it]
Evaluating: 100%|██████████| 1/1 [00:02<00:00,  2.48s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.46it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.54it/s]
Evaluating: 100%|██████████| 1/1 [00:03<00:00,  3.68s/it]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.22s/it]
Evaluating: 100%|██████████| 1/1 [00:03<00:00,  3.73s/it]
Evaluating: 100%|██████████| 1/1 [00:03<00:00,  3.06s/it]
Evaluating: 100%|██████████| 1/1 [00:10<00:00, 10.87s/it]
Evaluating: 100%|██████████| 1/1 [00:02<00:00,  2.11s/it]

Done 170/300

Evaluating: 100%|██████████| 1/1 [00:02<00:00,  2.01s/it]
Evaluating: 100%|██████████| 1/1 [00:03<00:00,  3.37s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.09it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  4.82it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.25s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.11it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.20it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.85it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  4.95it/s]

Done 180/300

Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.28s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.06it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.31it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.03it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.27s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.35it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.37it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.23it/s]

Done 190/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.27it/s]
Evaluating: 100%|██████████| 1/1 [00:01<00:00,  1.13s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.82it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  3.21it/s]
Evaluating: 100%|██████████| 1/1 [00:04<00:00,  4.73s/it]
Evaluating: 100%|██████████| 1/1 [00:02<00:00,  2.15s/it]
Evaluating: 100%|██████████| 1/1 [00:02<00:00,  2.70s/it]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  1.93it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00,  2.52it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]

Done 200/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.77it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.77it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.53it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.66it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.48it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.32it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.90it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.94it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.10it/s]

Done 210/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.42it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.06it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.06it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.84it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.58it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.61it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.96it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.36it/s]

Done 220/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.96it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.14it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.64it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.24it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.58it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.87it/s]

Done 230/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.34it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.11it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.74it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.50it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.15it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.47it/s]

Done 240/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.04it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.45it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.19it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.22it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.53it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.75it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.20it/s]

Done 250/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.90it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.09it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.64it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.71it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.76it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.33it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.20it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.60it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.26it/s]

Done 260/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.21it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.79it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.30it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.04it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.25it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.99it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.59it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.62it/s]

Done 270/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 22.06it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.52it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.23it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.98it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.66it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.12it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.91it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.66it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.74it/s]

Done 280/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.28it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.73it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.86it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.00it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.07it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.42it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 20.99it/s]

Done 290/300

Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.78it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.26it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.65it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.60it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.26it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.57it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.01it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 21.56it/s]
Evaluating: 100%|██████████| 1/1 [00:00<00:00, 19.85it/s]

In [85]:
# chanhing into datarframe and then saving the result into csvfile
df_baseline = pd.DataFrame(baseline_results)
df_baseline.sample(10)

,dataset,model,alignscore,claim
103,BillSum,RoBERTa-AlignScore,0.593202,Amends the Internal Revenue Code to provide (t...
146,BillSum,RoBERTa-AlignScore,0.409913,Securing Care for Seniors Act of 2015 (Sec. 2)...
249,CaseHOLD,RoBERTa-AlignScore,0.547095,holding the dismissed defendant was not preclu...
119,BillSum,RoBERTa-AlignScore,0.582659,New IDEA (Illegal Deduction Elimination Act) -...
86,Contract,RoBERTa-AlignScore,0.150021,All Confidential Information shall be expressl...
269,CaseHOLD,RoBERTa-AlignScore,0.006378,holding that deadly force was reasonable where...
27,Contract,RoBERTa-AlignScore,0.011914,Receiving Party shall not solicit some of Disc...
284,CaseHOLD,RoBERTa-AlignScore,0.461281,holding that admitting evidence of a defendant...
46,Contract,RoBERTa-AlignScore,0.003781,Receiving Party may create a copy of some Conf...
273,CaseHOLD,RoBERTa-AlignScore,0.833201,holding that an indian tribe is subject to sui...

In [86]:
df_baseline.to_csv("roberta_baseline_results.csv", index=False)

In [88]:
# average alignscore per dataset
df_baseline.groupby("dataset")["alignscore"].mean()

dataset
BillSum     0.517125
CaseHOLD    0.375707
Contract    0.265633
Name: alignscore, dtype: float64

Creating the LegalBERT fine-tuning the alignscore and then use that for training and evaluation

In [46]:
# checking models load correctly
from alignscore.model import BERTAlignModel

legalbert_model = BERTAlignModel(
    model='nlpaueb/legal-bert-base-uncased',
    using_pretrained=True
)

print("LegalBERT loaded")

LegalBERT loaded

In [45]:
legalroberta_model = BERTAlignModel(
    model='saibo/legal-roberta-base',
    using_pretrained=True
)

print("LegalRoBERTa loaded")

Some weights of RobertaModel were not initialized from the model checkpoint at saibo/legal-roberta-base and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

LegalRoBERTa loaded

for Training we using the contract_pairs and for evaluation/fine-tuning we use the df_all dataset

In [89]:
contract_train = []

for ex in islice(contract_nli, 500):
    contract_train.append({
        "context": ex["premise"],
        "claim": ex["hypothesis"],
        "label": ex["label"]
    })

df_contract_train = pd.DataFrame(contract_train)

print(df_contract_train.shape)
df_contract_train.head()

(500, 3)

,context,claim,label
0,2.3 Provided that the Recipient has a written ...,Receiving Party shall not reverse engineer any...,2
1,5. All Confidential Information in any form an...,Receiving Party shall destroy or return some C...,1
2,4. Nothing in this Agreement is to be construe...,Agreement shall not grant Receiving Party any ...,1
3,11. The Recipient shall not advertise or other...,Receiving Party shall not disclose the fact th...,1
4,"1. “Confidential Information”, whenever used i...",Confidential Information shall only include te...,2

In [90]:
df_contract_train["label"].value_counts()

label
2    221
1    213
0     66
Name: count, dtype: int64

In [91]:
df_contract_train.to_csv("contractnli_legal_train.csv", index=False)

In [97]:
def convert_contractnli_label(label):
    label = str(label).lower()

    if label in ["entailment", "entailed", "0"]:
        return 1   # aligned

    elif label in ["contradiction", "contradictory", "1"]:
        return 0   # not aligned

    elif label in ["neutral", "2"]:
        return 0   # treat neutral as not fully aligned

    else:
        return None


df_contract_train["align_label"] = df_contract_train["label"].apply(convert_contractnli_label)

df_contract_train.sample(10)

,context,claim,label,align_label
433,Recipients may make copies of Confidential Inf...,Receiving Party may create a copy of some Conf...,1,0
425,"Confidential Information would include, but wo...",Confidential Information shall only include te...,0,1
406,"As used in this Agreement, the term “Represent...",Receiving Party may share some Confidential In...,1,0
413,"If the Recipient fails to submit an offer, he ...",Receiving Party may retain some Confidential I...,1,0
31,Confidential Information does not include: > i...,Receiving Party may acquire information simila...,1,0
186,7.2. The Provider shall not disclose or otherw...,Receiving Party may create a copy of some Conf...,0,1
246,All Confidential Information shall remain the ...,All Confidential Information shall be expressl...,2,0
488,3. For the purposes of this Confidentiality an...,Receiving Party shall not use any Confidential...,1,0
30,"If Mentor is required by mandatory, non-appeal...",Receiving Party shall notify Disclosing Party ...,1,0
82,5. No Further Rights All Confidential Informat...,Receiving Party shall destroy or return some C...,2,0

In [98]:
df_contract_train["align_label"].value_counts()

align_label
0    434
1     66
Name: count, dtype: int64

In [99]:
df_contract_train.to_csv("contractnli_alignscore_train.csv", index=False)

In [115]:
# creating dataset + dataloader for LegalBERT fine-tuning
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer

MODEL_NAME = "nlpaueb/legal-bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
KeyError: 'args'

In [116]:
class LegalAlignDataset(Dataset):
    def __init__(self, dataframe, tokenizer, max_length=512):
        self.df = dataframe.reset_index(drop=True)
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        context = str(self.df.loc[idx, "context"])
        claim = str(self.df.loc[idx, "claim"])
        label = int(self.df.loc[idx, "align_label"])

        encoding = self.tokenizer(
            context,
            claim,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )

        item = {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "align_label": torch.tensor(label, dtype=torch.long)
        }

        if "token_type_ids" in encoding:
            item["token_type_ids"] = encoding["token_type_ids"].squeeze(0)

        return item

In [117]:
train_dataset = LegalAlignDataset(
    df_contract_train,
    tokenizer,
    max_length=512
)

train_loader = DataLoader(
    train_dataset,
    batch_size=4,
    shuffle=True
)

batch = next(iter(train_loader))
print(batch.keys())
print(batch["input_ids"].shape)
print(batch["align_label"])

dict_keys(['input_ids', 'attention_mask', 'align_label', 'token_type_ids'])
torch.Size([4, 512])
tensor([0, 0, 1, 0])

In [101]:
from transformers import AutoTokenizer
import tensorflow as tf
import pandas as pd

MODEL_NAME = "nlpaueb/legal-bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [103]:
texts_context = df_contract_train["context"].astype(str).tolist()
texts_claim = df_contract_train["claim"].astype(str).tolist()
labels = df_contract_train["align_label"].astype(int).tolist()

encodings = tokenizer(
    texts_context,
    texts_claim,
    truncation=True,
    padding=True,
    max_length=512,
    return_tensors="tf"
)

y = tf.constant(labels)

In [105]:
from sklearn.model_selection import train_test_split

input_ids = encodings["input_ids"].numpy()
attention_mask = encodings["attention_mask"].numpy()

X_train_ids, X_val_ids, X_train_mask, X_val_mask, y_train, y_val = train_test_split(
    input_ids,
    attention_mask,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

In [110]:
from transformers import TFAutoModel
from tensorflow.keras.layers import Input, Dense, Dropout
from tensorflow.keras.models import Model

bert = TFAutoModel.from_pretrained(MODEL_NAME)

input_ids_layer = Input(shape=(512,), dtype=tf.int32, name="input_ids")
attention_mask_layer = Input(shape=(512,), dtype=tf.int32, name="attention_mask")

bert_output = bert(
    input_ids=input_ids_layer,
    attention_mask=attention_mask_layer
)

cls_output = bert_output.last_hidden_state[:, 0, :]

x = Dropout(0.2)(cls_output)
output = Dense(1, activation="sigmoid")(x)

legalbert_keras_model = Model(
    inputs=[input_ids_layer, attention_mask_layer],
    outputs=output
)

legalbert_keras_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=2e-5),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

legalbert_keras_model.summary()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

KeyError: 'args'

In [ ]:
history = legalbert_keras_model.fit(
    {
        "input_ids": X_train_ids,
        "attention_mask": X_train_mask
    },
    tf.constant(y_train),
    validation_data=(
        {
            "input_ids": X_val_ids,
            "attention_mask": X_val_mask
        },
        tf.constant(y_val)
    ),
    epochs=3,
    batch_size=4
)

In [108]:
def legalbert_alignscore(context, claim):
    encoding = tokenizer(
        [context],
        [claim],
        truncation=True,
        padding="max_length",
        max_length=512,
        return_tensors="tf"
    )

    score = legalbert_keras_model.predict({
        "input_ids": encoding["input_ids"],
        "attention_mask": encoding["attention_mask"]
    })

    return float(score[0][0])

In [109]:
context = "The court held that the contract was valid and enforceable."
claim = "The contract was valid."

score = legalbert_alignscore(context, claim)
print(score)

NameError: name 'legalbert_keras_model' is not defined